"""Versioned cross-agent contracts."""

from packages.contracts.agui import (
    AG_UI_ACTION_SCHEMA_VERSION,
    AG_UI_STATE_SCHEMA_VERSION,
    ActionType,
    AgentDeskAction,
    AgentDeskViewState,
    SpecialistView,
)
from packages.contracts.artifacts import (
    DOMAIN_SCHEMA_VERSION,
    ArtifactEnvelope,
    ArtifactProvenance,
)
from packages.contracts.domain import (
    AnalysisRequest,
    Claim,
    CriterionScore,
    DecisionAnalysis,
    Evidence,
    EvidenceBundle,
    FinalSynthesis,
    RecommendationChallenge,
    ResearchRequest,
    VerificationReport,
    VerificationResult,
)
from packages.contracts.intake import (
    INTAKE_SCHEMA_VERSION,
    MAX_INTAKE_ARTIFACT_BYTES,
    MAX_INTAKE_RESPONSE_BYTES,
    MAX_INTAKE_TEXT_LENGTH,
    MAX_SCOPE_CHOICES,
    MAX_SCOPE_FIELDS,
    SCOPE_PROPOSAL_ARTIFACT_NAME,
    IntakeResponse,
    ScopeField,
    ScopeProposal,
    ScopeProposalArtifact,
    parse_intake_response,
    parse_scope_proposal_artifact,
    validate_intake_response,
)

__all__ = [
    "AG_UI_ACTION_SCHEMA_VERSION",
    "AG_UI_STATE_SCHEMA_VERSION",
    "ActionType",
    "AgentDeskAction",
    "AgentDeskViewState",
    "DOMAIN_SCHEMA_VERSION",
    "ArtifactEnvelope",
    "ArtifactProvenance",
    "AnalysisRequest",
    "Claim",
    "CriterionScore",
    "DecisionAnalysis",
    "Evidence",
    "EvidenceBundle",
    "FinalSynthesis",
    "INTAKE_SCHEMA_VERSION",
    "IntakeResponse",
    "MAX_INTAKE_ARTIFACT_BYTES",
    "MAX_INTAKE_RESPONSE_BYTES",
    "MAX_INTAKE_TEXT_LENGTH",
    "MAX_SCOPE_CHOICES",
    "MAX_SCOPE_FIELDS",
    "RecommendationChallenge",
    "ResearchRequest",
    "SCOPE_PROPOSAL_ARTIFACT_NAME",
    "ScopeField",
    "ScopeProposal",
    "ScopeProposalArtifact",
    "SpecialistView",
    "VerificationReport",
    "VerificationResult",
    "parse_intake_response",
    "parse_scope_proposal_artifact",
    "validate_intake_response",
]
